<?php

namespace Database\Seeders;

use App\Models\Barang\Warna;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WarnaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Warna::truncate();

        Warna::upsert(
            [
                ['kode' => 'WRN.1', 'nama' => '1 PUTIH', 'keterangan' => '1 PUTIH'],
                ['kode' => 'WRN.2', 'nama' => '2 PINK BABY', 'keterangan' => '2 PINK BABY'],
                ['kode' => 'WRN.3', 'nama' => '3 BIRU BABY', 'keterangan' => '3 BIRU BABY'],
                ['kode' => 'WRN.4', 'nama' => '4 HIJAU TOSCA', 'keterangan' => '4 HIJAU TOSCA'],
                ['kode' => 'WRN.5', 'nama' => '5 CREAM', 'keterangan' => '5 CREAM'],
                ['kode' => 'WRN.6', 'nama' => '6 MAGENTA', 'keterangan' => '6 MAGENTA'],
                ['kode' => 'WRN.7', 'nama' => '7 TURQIS', 'keterangan' => '7 TURQIS'],
                ['kode' => 'WRN.8', 'nama' => '8 HIJAU FUJI', 'keterangan' => '8 HIJAU FUJI'],
                ['kode' => 'WRN.9', 'nama' => '9 KUNING KENARI', 'keterangan' => '9 KUNING KENARI'],
                ['kode' => 'WRN.10', 'nama' => '10 MERAH CABE', 'keterangan' => '10 MERAH CABE'],
                ['kode' => 'WRN.11', 'nama' => '11 BENHUR', 'keterangan' => '11 BENHUR'],
                ['kode' => 'WRN.12', 'nama' => '12 HIJAU ARMY', 'keterangan' => '12 HIJAU ARMY'],
                ['kode' => 'WRN.13', 'nama' => '13 KUNING BUSUK', 'keterangan' => '13 KUNING BUSUK'],
                ['kode' => 'WRN.14', 'nama' => '14 MAROON', 'keterangan' => '14 MAROON'],
                ['kode' => 'WRN.15', 'nama' => '15 DONGKER', 'keterangan' => '15 DONGKER'],
                ['kode' => 'WRN.16', 'nama' => '16 HIJAU BOTOL', 'keterangan' => '16 HIJAU BOTOL'],
                ['kode' => 'WRN.17', 'nama' => '17 ORANGE', 'keterangan' => '17 ORANGE'],
                ['kode' => 'WRN.18', 'nama' => '18 COKLAT', 'keterangan' => '18 COKLAT'],
                ['kode' => 'WRN.19', 'nama' => '19 COKLAT KOPI', 'keterangan' => '19 COKLAT KOPI'],
                ['kode' => 'WRN.20', 'nama' => '20 HITAM', 'keterangan' => '20 HITAM'],
                ['kode' => 'WRN.21', 'nama' => '21 ABU MUDA', 'keterangan' => '21 ABU MUDA'],
                ['kode' => 'WRN.22', 'nama' => '22 ABU TUA', 'keterangan' => '22 ABU TUA'],
                ['kode' => 'WRN.23', 'nama' => '23 MISTY MUDA', 'keterangan' => '23 MISTY MUDA'],
                ['kode' => 'WRN.24', 'nama' => '24 MISTY TUA', 'keterangan' => '24 MISTY TUA'],
                ['kode' => 'WRN.25', 'nama' => '25 PUTIH', 'keterangan' => '25 PUTIH'],
                ['kode' => 'WRN.26', 'nama' => '26 PINK BABY', 'keterangan' => '26 PINK BABY'],
                ['kode' => 'WRN.27', 'nama' => '27 BIRU BABY', 'keterangan' => '27 BIRU BABY'],
                ['kode' => 'WRN.28', 'nama' => '28 ORANGE', 'keterangan' => '28 ORANGE'],
                ['kode' => 'WRN.29', 'nama' => '29 LILAC', 'keterangan' => '29 LILAC'],
                ['kode' => 'WRN.30', 'nama' => '30 MERAH CABE', 'keterangan' => '30 MERAH CABE'],
                ['kode' => 'WRN.31', 'nama' => '31 BENHUR', 'keterangan' => '31 BENHUR'],
                ['kode' => 'WRN.32', 'nama' => '32 TOSCA', 'keterangan' => '32 TOSCA'],
                ['kode' => 'WRN.33', 'nama' => '33 SALEM', 'keterangan' => '33 SALEM'],
                ['kode' => 'WRN.34', 'nama' => '34 MAROON', 'keterangan' => '34 MAROON'],
                ['kode' => 'WRN.35', 'nama' => '35 NAVY', 'keterangan' => '35 NAVY'],
                ['kode' => 'WRN.36', 'nama' => '36 HIJAU FUJI', 'keterangan' => '36 HIJAU FUJI'],
                ['kode' => 'WRN.37', 'nama' => '37 COKLAT MUDA', 'keterangan' => '37 COKLAT MUDA'],
                ['kode' => 'WRN.38', 'nama' => '38 MAGENTA', 'keterangan' => '38 MAGENTA'],
                ['kode' => 'WRN.39', 'nama' => '39 TURQIS', 'keterangan' => '39 TURQIS'],
                ['kode' => 'WRN.40', 'nama' => '40 HIJAU TUA', 'keterangan' => '40 HIJAU TUA'],
                ['kode' => 'WRN.41', 'nama' => '9 ABU TUA', 'keterangan' => '9 ABU TUA'],
                ['kode' => 'WRN.42', 'nama' => '1 PUTIH BLUISH', 'keterangan' => '1 PUTIH BLUISH'],
                ['kode' => 'WRN.43', 'nama' => '2 PUTIH BLUISH-2', 'keterangan' => '2 PUTIH BLUISH-2'],
                ['kode' => 'WRN.44', 'nama' => '3 PUTIH COTINUOUS', 'keterangan' => '3 PUTIH COTINUOUS'],
                ['kode' => 'WRN.45', 'nama' => '4 ABU ASAP', 'keterangan' => '4 ABU ASAP'],
                ['kode' => 'WRN.46', 'nama' => '18 UNGU MUDA', 'keterangan' => '18 UNGU MUDA'],
                ['kode' => 'WRN.47', 'nama' => '22 HIJAU MINT', 'keterangan' => '22 HIJAU MINT'],
                ['kode' => 'WRN.48', 'nama' => '26 PINK', 'keterangan' => '26 PINK'],
                ['kode' => 'WRN.49', 'nama' => '34 COKLAT ABU', 'keterangan' => '34 COKLAT ABU'],
                ['kode' => 'WRN.50', 'nama' => '35 COKLAT SEDANG', 'keterangan' => '35 COKLAT SEDANG'],
                ['kode' => 'WRN.51', 'nama' => '39 KUNING KENARI-1', 'keterangan' => '39 KUNING KENARI-1'],
                ['kode' => 'WRN.52', 'nama' => '41 KUNING KENARI-3', 'keterangan' => '41 KUNING KENARI-3'],
                ['kode' => 'WRN.53', 'nama' => '42 KUNING MAS', 'keterangan' => '42 KUNING MAS'],
                ['kode' => 'WRN.54', 'nama' => '43 KUNING LEMON', 'keterangan' => '43 KUNING LEMON'],
                ['kode' => 'WRN.55', 'nama' => '44 KUNING BUSUK-1', 'keterangan' => '44 KUNING BUSUK-1'],
                ['kode' => 'WRN.56', 'nama' => '49 TOSCA SEDANG-1', 'keterangan' => '49 TOSCA SEDANG-1'],
                ['kode' => 'WRN.57', 'nama' => '52 BIRU SEDANG', 'keterangan' => '52 BIRU SEDANG'],
                ['kode' => 'WRN.58', 'nama' => '55 HIJAU STABILO-3', 'keterangan' => '55 HIJAU STABILO-3'],
                ['kode' => 'WRN.59', 'nama' => '58 BLUE REEF', 'keterangan' => '58 BLUE REEF'],
                ['kode' => 'WRN.60', 'nama' => '60 DUSTY PINK-2', 'keterangan' => '60 DUSTY PINK-2'],
                ['kode' => 'WRN.61', 'nama' => '61 BLUSH PINK', 'keterangan' => '61 BLUSH PINK'],
                ['kode' => 'WRN.62', 'nama' => '65 MINERAL GREEN', 'keterangan' => '65 MINERAL GREEN'],
                ['kode' => 'WRN.63', 'nama' => '92 HITAM REAKTIF-1', 'keterangan' => '92 HITAM REAKTIF-1'],
                ['kode' => 'WRN.64', 'nama' => '93 HITAM REAKTIF-2', 'keterangan' => '93 HITAM REAKTIF-2'],
                ['kode' => 'WRN.65', 'nama' => '95 UNGU TUA-1', 'keterangan' => '95 UNGU TUA-1'],
                ['kode' => 'WRN.66', 'nama' => '97 TURQIS TUA-1', 'keterangan' => '97 TURQIS TUA-1'],
                ['kode' => 'WRN.67', 'nama' => '100 ABU TUA-1', 'keterangan' => '100 ABU TUA-1'],
                ['kode' => 'WRN.68', 'nama' => '102 FANTA-1', 'keterangan' => '102 FANTA-1'],
                ['kode' => 'WRN.69', 'nama' => '103 FANTA-2', 'keterangan' => '103 FANTA-2'],
                ['kode' => 'WRN.70', 'nama' => '104 MERAH CABE-1', 'keterangan' => '104 MERAH CABE-1'],
                ['kode' => 'WRN.71', 'nama' => '107 HIJAU TOSCA-1', 'keterangan' => '107 HIJAU TOSCA-1'],
                ['kode' => 'WRN.72', 'nama' => '109 HIJAU BOTOL-1', 'keterangan' => '109 HIJAU BOTOL-1'],
                ['kode' => 'WRN.73', 'nama' => '110 HIJAU BOTOL-2', 'keterangan' => '110 HIJAU BOTOL-2'],
                ['kode' => 'WRN.74', 'nama' => '112 HIJAU TNI-2', 'keterangan' => '112 HIJAU TNI-2'],
                ['kode' => 'WRN.75', 'nama' => '113 COKLAT KOPI-1', 'keterangan' => '113 COKLAT KOPI-1'],
                ['kode' => 'WRN.76', 'nama' => '114 COKLAT KOPI-2', 'keterangan' => '114 COKLAT KOPI-2'],
                ['kode' => 'WRN.77', 'nama' => '115 KUNING MANGO', 'keterangan' => '115 KUNING MANGO'],
                ['kode' => 'WRN.78', 'nama' => '116 ORANGE', 'keterangan' => '116 ORANGE'],
                ['kode' => 'WRN.79', 'nama' => '117 MAROON-1', 'keterangan' => '117 MAROON-1'],
                ['kode' => 'WRN.80', 'nama' => '121 MERAH HATI', 'keterangan' => '121 MERAH HATI'],
                ['kode' => 'WRN.81', 'nama' => '122 ROYAL BLUE', 'keterangan' => '122 ROYAL BLUE'],
                ['kode' => 'WRN.82', 'nama' => '123 BLUE BLACK', 'keterangan' => '123 BLUE BLACK'],
                ['kode' => 'WRN.83', 'nama' => '125 TOFFEE', 'keterangan' => '125 TOFFEE'],
                ['kode' => 'WRN.84', 'nama' => '137 MERAH SPECIAL', 'keterangan' => '137 MERAH SPECIAL'],
                ['kode' => 'WRN.85', 'nama' => '138 HITAM BALI', 'keterangan' => '138 HITAM BALI'],
                ['kode' => 'WRN.86', 'nama' => '139 HIJAU FUJI-1', 'keterangan' => '139 HIJAU FUJI-1'],
                ['kode' => 'WRN.87', 'nama' => '143 TURQIS SPECIAL', 'keterangan' => '143 TURQIS SPECIAL'],
                ['kode' => 'WRN.88', 'nama' => '41 KUNING BUSUK', 'keterangan' => '41 KUNING BUSUK'],
                ['kode' => 'WRN.89', 'nama' => '42 COKLAT KOPI', 'keterangan' => '42 COKLAT KOPI'],
                ['kode' => 'WRN.90', 'nama' => '43 HITAM', 'keterangan' => '43 HITAM'],
                ['kode' => 'WRN.91', 'nama' => '44 HIJAU ARMY', 'keterangan' => '44 HIJAU ARMY'],
                ['kode' => 'WRN.92', 'nama' => '45 ABU MUDA', 'keterangan' => '45 ABU MUDA'],
                ['kode' => 'WRN.93', 'nama' => '1 HITAM BALI', 'keterangan' => '1 HITAM BALI'],
                ['kode' => 'WRN.94', 'nama' => '2 NAVY', 'keterangan' => '2 NAVY'],
                ['kode' => 'WRN.95', 'nama' => '3 HIJAU BOTOL', 'keterangan' => '3 HIJAU BOTOL'],
                ['kode' => 'WRN.96', 'nama' => '4 MISTYY 71 PUTIH', 'keterangan' => '4 MISTYY 71 PUTIH'],
                ['kode' => 'WRN.97', 'nama' => '5 KUNING BUSUK', 'keterangan' => '5 KUNING BUSUK'],
                ['kode' => 'WRN.98', 'nama' => '6 PUTIH BLUISH', 'keterangan' => '6 PUTIH BLUISH'],
                ['kode' => 'WRN.99', 'nama' => '2 MERAH SPECIAL', 'keterangan' => '2 MERAH SPECIAL'],
                ['kode' => 'WRN.100', 'nama' => '3 HITAM BALI', 'keterangan' => '3 HITAM BALI'],
                ['kode' => 'WRN.101', 'nama' => '4 HIJAU BOTOL', 'keterangan' => '4 HIJAU BOTOL'],
                ['kode' => 'WRN.102', 'nama' => '6 MAROON', 'keterangan' => '6 MAROON'],
                ['kode' => 'WRN.103', 'nama' => '7 NAVY', 'keterangan' => '7 NAVY'],
                ['kode' => 'WRN.104', 'nama' => '8 HIJAU TNI', 'keterangan' => '8 HIJAU TNI'],
                ['kode' => 'WRN.105', 'nama' => '3 PUTIH CONTINUOUS', 'keterangan' => '3 PUTIH CONTINUOUS'],
                ['kode' => 'WRN.106', 'nama' => '7 BROKEN WHITE-1', 'keterangan' => '7 BROKEN WHITE-1'],
                ['kode' => 'WRN.107', 'nama' => '19 ORANGE MUDA', 'keterangan' => '19 ORANGE MUDA'],
                ['kode' => 'WRN.108', 'nama' => '21 TURQIS MUDA', 'keterangan' => '21 TURQIS MUDA'],
                ['kode' => 'WRN.109', 'nama' => '23 HIJAU MUDA', 'keterangan' => '23 HIJAU MUDA'],
                ['kode' => 'WRN.110', 'nama' => '25 SALEM MUDA', 'keterangan' => '25 SALEM MUDA'],
                ['kode' => 'WRN.111', 'nama' => '30 SALEM-1', 'keterangan' => '30 SALEM-1'],
                ['kode' => 'WRN.112', 'nama' => '37 ABU SEDANG-1', 'keterangan' => '37 ABU SEDANG-1'],
                ['kode' => 'WRN.113', 'nama' => '46 KUNING KUNYIT', 'keterangan' => '46 KUNING KUNYIT'],
                ['kode' => 'WRN.114', 'nama' => '47 BIRU SEDANG', 'keterangan' => '47 BIRU SEDANG'],
                ['kode' => 'WRN.115', 'nama' => '50 TOSCA SEDANG-2', 'keterangan' => '50 TOSCA SEDANG-2'],
                ['kode' => 'WRN.116', 'nama' => '51 TURQIS SEDANG', 'keterangan' => '51 TURQIS SEDANG'],
                ['kode' => 'WRN.117', 'nama' => '53 HIJAU STABILO-1', 'keterangan' => '53 HIJAU STABILO-1'],
                ['kode' => 'WRN.118', 'nama' => '57 CORAL RED', 'keterangan' => '57 CORAL RED'],
                ['kode' => 'WRN.119', 'nama' => '59 DUSTY PINK-1', 'keterangan' => '59 DUSTY PINK-1'],
                ['kode' => 'WRN.120', 'nama' => '62 BUBBLEGUM PINK', 'keterangan' => '62 BUBBLEGUM PINK'],
                ['kode' => 'WRN.121', 'nama' => '63 DUSTY MAGENTA', 'keterangan' => '63 DUSTY MAGENTA'],
                ['kode' => 'WRN.122', 'nama' => '64 BIRU MARINIR', 'keterangan' => '64 BIRU MARINIR'],
                ['kode' => 'WRN.123', 'nama' => '66 DUSTY GREEN', 'keterangan' => '66 DUSTY GREEN'],
                ['kode' => 'WRN.124', 'nama' => '67 PINE GREEN', 'keterangan' => '67 PINE GREEN'],
                ['kode' => 'WRN.125', 'nama' => '88 HIJAU WARDAH', 'keterangan' => '88 HIJAU WARDAH'],
                ['kode' => 'WRN.126', 'nama' => '91 BRONZE MIST', 'keterangan' => '91 BRONZE MIST'],
                ['kode' => 'WRN.127', 'nama' => '99 TURQIS TUA-3', 'keterangan' => '99 TURQIS TUA-3'],
                ['kode' => 'WRN.128', 'nama' => '108 HIJAU TOSCA-2', 'keterangan' => '108 HIJAU TOSCA-2'],
                ['kode' => 'WRN.129', 'nama' => '119 MAROON-3', 'keterangan' => '119 MAROON-3'],
                ['kode' => 'WRN.130', 'nama' => '120 MAROON-4', 'keterangan' => '120 MAROON-4'],
                ['kode' => 'WRN.131', 'nama' => '127 CELESTIAL BLUE', 'keterangan' => '127 CELESTIAL BLUE'],
                ['kode' => 'WRN.132', 'nama' => '141 BENHUR-1', 'keterangan' => '141 BENHUR-1'],
                ['kode' => 'WRN.133', 'nama' => '5 ABU MUDA', 'keterangan' => '5 ABU MUDA'],
                ['kode' => 'WRN.134', 'nama' => '8 BROKEN WHITE-2', 'keterangan' => '8 BROKEN WHITE-2'],
                ['kode' => 'WRN.135', 'nama' => '9 BIRU MUDA-1', 'keterangan' => '9 BIRU MUDA-1'],
                ['kode' => 'WRN.136', 'nama' => '10 BIRU MUDA-2', 'keterangan' => '10 BIRU MUDA-2'],
                ['kode' => 'WRN.137', 'nama' => '11 BIRU MUDA-3', 'keterangan' => '11 BIRU MUDA-3'],
                ['kode' => 'WRN.138', 'nama' => '12 CREAM', 'keterangan' => '12 CREAM'],
                ['kode' => 'WRN.139', 'nama' => '13 COKLAT SUSU', 'keterangan' => '13 COKLAT SUSU'],
                ['kode' => 'WRN.140', 'nama' => '14 COKLAT MUDA', 'keterangan' => '14 COKLAT MUDA'],
                ['kode' => 'WRN.141', 'nama' => '16 KUNING MUDA-1', 'keterangan' => '16 KUNING MUDA-1'],
                ['kode' => 'WRN.142', 'nama' => '17 KUNING MUDA-2', 'keterangan' => '17 KUNING MUDA-2'],
                ['kode' => 'WRN.143', 'nama' => '20 TOSCA MUDA', 'keterangan' => '20 TOSCA MUDA'],
                ['kode' => 'WRN.144', 'nama' => '27 ROSE MUDA', 'keterangan' => '27 ROSE MUDA'],
                ['kode' => 'WRN.145', 'nama' => '31 SALEM-2', 'keterangan' => '31 SALEM-2'],
                ['kode' => 'WRN.146', 'nama' => '32 UNGU SEDANG', 'keterangan' => '32 UNGU SEDANG'],
                ['kode' => 'WRN.147', 'nama' => '38 ABU SEDANG-2', 'keterangan' => '38 ABU SEDANG-2'],
                ['kode' => 'WRN.148', 'nama' => '40 KUNING KENARI-2', 'keterangan' => '40 KUNING KENARI-2'],
                ['kode' => 'WRN.149', 'nama' => '45 KUNING BUSUK-2', 'keterangan' => '45 KUNING BUSUK-2'],
                ['kode' => 'WRN.150', 'nama' => '54 HIJAU STABILO-2', 'keterangan' => '54 HIJAU STABILO-2'],
                ['kode' => 'WRN.151', 'nama' => '69 PEANUT LATTE', 'keterangan' => '69 PEANUT LATTE'],
                ['kode' => 'WRN.152', 'nama' => '70 PECCAN MOCCA', 'keterangan' => '70 PECCAN MOCCA'],
                ['kode' => 'WRN.153', 'nama' => '73 RUSTY', 'keterangan' => '73 RUSTY'],
                ['kode' => 'WRN.154', 'nama' => '85 HIJAU SEMPURNA', 'keterangan' => '85 HIJAU SEMPURNA'],
                ['kode' => 'WRN.155', 'nama' => '86 HIJAU PUCUK', 'keterangan' => '86 HIJAU PUCUK'],
                ['kode' => 'WRN.156', 'nama' => '87 HIJAU ALPUKAT', 'keterangan' => '87 HIJAU ALPUKAT'],
                ['kode' => 'WRN.157', 'nama' => '94 MERAH BATA', 'keterangan' => '94 MERAH BATA'],
                ['kode' => 'WRN.158', 'nama' => '96 UNGU TUA-2', 'keterangan' => '96 UNGU TUA-2'],
                ['kode' => 'WRN.159', 'nama' => '98 TURQIS TUA-2', 'keterangan' => '98 TURQIS TUA-2'],
                ['kode' => 'WRN.160', 'nama' => '101 ABU TUA-2', 'keterangan' => '101 ABU TUA-2'],
                ['kode' => 'WRN.161', 'nama' => '105 COKLAT SUSU', 'keterangan' => '105 COKLAT SUSU'],
                ['kode' => 'WRN.162', 'nama' => '106 GREEN TOSCA', 'keterangan' => '106 GREEN TOSCA'],
                ['kode' => 'WRN.163', 'nama' => '111 HIJAU TNI-1', 'keterangan' => '111 HIJAU TNI-1'],
                ['kode' => 'WRN.164', 'nama' => '118 MAROON-2', 'keterangan' => '118 MAROON-2'],
                ['kode' => 'WRN.165', 'nama' => '124 CINNAMON BROWN', 'keterangan' => '124 CINNAMON BROWN'],
                ['kode' => 'WRN.166', 'nama' => '126 GINGER TEA', 'keterangan' => '126 GINGER TEA'],
                ['kode' => 'WRN.167', 'nama' => '130 DARK MUSTARD', 'keterangan' => '130 DARK MUSTARD'],
                ['kode' => 'WRN.168', 'nama' => '132 NAVY', 'keterangan' => '132 NAVY'],
                ['kode' => 'WRN.169', 'nama' => '133 OLD NAVY', 'keterangan' => '133 OLD NAVY'],
                ['kode' => 'WRN.170', 'nama' => '140 HIJAU FUJI-2', 'keterangan' => '140 HIJAU FUJI-2'],
                ['kode' => 'WRN.171', 'nama' => '142 BENHUR-2', 'keterangan' => '142 BENHUR-2'],
                ['kode' => 'WRN.172', 'nama' => '6 ABU BIRU', 'keterangan' => '6 ABU BIRU'],
                ['kode' => 'WRN.173', 'nama' => '12 CREAM', 'keterangan' => '12 CREAM'],
                ['kode' => 'WRN.174', 'nama' => '15 SAFARI BROWN', 'keterangan' => '15 SAFARI BROWN'],
                ['kode' => 'WRN.175', 'nama' => '24 PEACH MUDA', 'keterangan' => '24 PEACH MUDA'],
                ['kode' => 'WRN.176', 'nama' => '28 FAIRY PINK', 'keterangan' => '28 FAIRY PINK'],
                ['kode' => 'WRN.177', 'nama' => '29 SEA PINK', 'keterangan' => '29 SEA PINK'],
                ['kode' => 'WRN.178', 'nama' => '33 DUSTY VIOLET', 'keterangan' => '33 DUSTY VIOLET'],
                ['kode' => 'WRN.179', 'nama' => '36 BEAVER BROWN', 'keterangan' => '36 BEAVER BROWN'],
                ['kode' => 'WRN.180', 'nama' => '48 BIRU TEAL', 'keterangan' => '48 BIRU TEAL'],
                ['kode' => 'WRN.181', 'nama' => '56 HIJAU TKD', 'keterangan' => '56 HIJAU TKD'],
                ['kode' => 'WRN.182', 'nama' => '68 ATLANTIS GREEN', 'keterangan' => '68 ATLANTIS GREEN'],
                ['kode' => 'WRN.183', 'nama' => '71 SMOKE BLUE', 'keterangan' => '71 SMOKE BLUE'],
                ['kode' => 'WRN.184', 'nama' => '72 TERRA COTTA', 'keterangan' => '72 TERRA COTTA'],
                ['kode' => 'WRN.185', 'nama' => '74 CAMEO BLUE', 'keterangan' => '74 CAMEO BLUE'],
                ['kode' => 'WRN.186', 'nama' => '75 DUSTY PEACH', 'keterangan' => '75 DUSTY PEACH'],
                ['kode' => 'WRN.187', 'nama' => '76 NOSTALGIA ROSE', 'keterangan' => '76 NOSTALGIA ROSE'],
                ['kode' => 'WRN.188', 'nama' => '77 CLOUD BLUE', 'keterangan' => '77 CLOUD BLUE'],
                ['kode' => 'WRN.189', 'nama' => '78 OPULENCE GREEN', 'keterangan' => '78 OPULENCE GREEN'],
                ['kode' => 'WRN.190', 'nama' => '79 LAVENDER LILAC', 'keterangan' => '79 LAVENDER LILAC'],
                ['kode' => 'WRN.191', 'nama' => '80 ASPEN GREEN', 'keterangan' => '80 ASPEN GREEN'],
                ['kode' => 'WRN.192', 'nama' => '81 OCEAN BLUE', 'keterangan' => '81 OCEAN BLUE'],
                ['kode' => 'WRN.193', 'nama' => '82 STORM BLUE', 'keterangan' => '82 STORM BLUE'],
                ['kode' => 'WRN.194', 'nama' => '83 AUTUMN GREEN', 'keterangan' => '83 AUTUMN GREEN'],
                ['kode' => 'WRN.195', 'nama' => '84 STORM GREEN', 'keterangan' => '84 STORM GREEN'],
                ['kode' => 'WRN.196', 'nama' => '89 NIAGARA BLUE', 'keterangan' => '89 NIAGARA BLUE'],
                ['kode' => 'WRN.197', 'nama' => '90 VETIVER GRAY', 'keterangan' => '90 VETIVER GRAY'],
                ['kode' => 'WRN.198', 'nama' => '115 COKLAT KOPI-1', 'keterangan' => '115 COKLAT KOPI-1'],
                ['kode' => 'WRN.199', 'nama' => '116 KUNING MANGO', 'keterangan' => '116 KUNING MANGO'],
                ['kode' => 'WRN.200', 'nama' => '180 MAROON-4', 'keterangan' => '180 MAROON-4'],
                ['kode' => 'WRN.201', 'nama' => '128 BURGUNDY', 'keterangan' => '128 BURGUNDY'],
                ['kode' => 'WRN.202', 'nama' => '129 PLUM RED', 'keterangan' => '129 PLUM RED'],
                ['kode' => 'WRN.203', 'nama' => '131 ORANGE BATA', 'keterangan' => '131 ORANGE BATA'],
                ['kode' => 'WRN.204', 'nama' => '134 DARK TOSCA', 'keterangan' => '134 DARK TOSCA'],
                ['kode' => 'WRN.205', 'nama' => '135 CLASSIC BLUE', 'keterangan' => '135 CLASSIC BLUE'],
                ['kode' => 'WRN.206', 'nama' => '136 RED WINE', 'keterangan' => '136 RED WINE'],
                ['kode' => 'WRN.207', 'nama' => 'TURQIS SPECIAL', 'keterangan' => 'TURQIS SPECIAL'],
                ['kode' => 'WRN.208', 'nama' => '144 HITAM MARBLE', 'keterangan' => '144 HITAM MARBLE'],
                ['kode' => 'WRN.209', 'nama' => '145 MISTY 61', 'keterangan' => '145 MISTY 61'],
                ['kode' => 'WRN.210', 'nama' => '146 MISTY 71', 'keterangan' => '146 MISTY 71'],
                ['kode' => 'WRN.211', 'nama' => '147 MISTY 71 PUTIH', 'keterangan' => '147 MISTY 71 PUTIH'],
                ['kode' => 'WRN.212', 'nama' => '148 MISTY 81', 'keterangan' => '148 MISTY 81'],
                ['kode' => 'WRN.213', 'nama' => '149 MISTY 61 PUTIH', 'keterangan' => '149 MISTY 61 PUTIH'],
                ['kode' => 'WRN.214', 'nama' => 'PUTIH', 'keterangan' => 'PUTIH'],
                ['kode' => 'WRN.215', 'nama' => 'COKLAT PNS', 'keterangan' => 'COKLAT PNS'],
                ['kode' => 'WRN.216', 'nama' => 'HITAM', 'keterangan' => 'HITAM'],
                ['kode' => 'WRN.217', 'nama' => '1 SKY BLUE', 'keterangan' => '1 SKY BLUE'],
                ['kode' => 'WRN.218', 'nama' => '2 FANTA', 'keterangan' => '2 FANTA'],
                ['kode' => 'WRN.219', 'nama' => '3 PUTIH', 'keterangan' => '3 PUTIH'],
                ['kode' => 'WRN.220', 'nama' => '4 HIJAU STABILLO', 'keterangan' => '4 HIJAU STABILLO'],
                ['kode' => 'WRN.221', 'nama' => '5 ORANGE STABILLO', 'keterangan' => '5 ORANGE STABILLO'],
                ['kode' => 'WRN.222', 'nama' => '6 KUNING', 'keterangan' => '6 KUNING'],
                ['kode' => 'WRN.223', 'nama' => '7 ABU', 'keterangan' => '7 ABU'],
                ['kode' => 'WRN.224', 'nama' => '8 MERAH', 'keterangan' => '8 MERAH'],
                ['kode' => 'WRN.225', 'nama' => '9 NAVY', 'keterangan' => '9 NAVY'],
                ['kode' => 'WRN.226', 'nama' => '10 HITAM', 'keterangan' => '10 HITAM'],
                ['kode' => 'WRN.227', 'nama' => '11 HIJAU TNI', 'keterangan' => '11 HIJAU TNI'],
                ['kode' => 'WRN.228', 'nama' => 'ABU MUDA', 'keterangan' => 'ABU MUDA'],
                ['kode' => 'WRN.229', 'nama' => '4 TOSCA', 'keterangan' => '4 TOSCA'],
                ['kode' => 'WRN.230', 'nama' => '7 DEEP BLUE', 'keterangan' => '7 DEEP BLUE'],
                ['kode' => 'WRN.231', 'nama' => '11 TURQIS', 'keterangan' => '11 TURQIS'],
                ['kode' => 'WRN.232', 'nama' => '15 BENHUR', 'keterangan' => '15 BENHUR'],
                ['kode' => 'WRN.233', 'nama' => '18 COKLAT KOPI', 'keterangan' => '18 COKLAT KOPI'],
                ['kode' => 'WRN.234', 'nama' => '19 DONGKER', 'keterangan' => '19 DONGKER'],
                ['kode' => 'WRN.235', 'nama' => '21 VIOLET', 'keterangan' => '21 VIOLET'],
                ['kode' => 'WRN.236', 'nama' => '22 LILAC', 'keterangan' => '22 LILAC'],
                ['kode' => 'WRN.237', 'nama' => '23 ABU MUDA', 'keterangan' => '23 ABU MUDA'],
                ['kode' => 'WRN.238', 'nama' => '24 ABU TUA', 'keterangan' => '24 ABU TUA'],
                ['kode' => 'WRN.239', 'nama' => '25 MISTY 71', 'keterangan' => '25 MISTY 71'],
                ['kode' => 'WRN.240', 'nama' => '26 MISTY TUA', 'keterangan' => '26 MISTY TUA'],
                ['kode' => 'WRN.241', 'nama' => '27 PUTIH BLUISH', 'keterangan' => '27 PUTIH BLUISH'],
                ['kode' => 'WRN.242', 'nama' => '28 CREAM', 'keterangan' => '28 CREAM'],
                ['kode' => 'WRN.243', 'nama' => '29 KUNING MAS', 'keterangan' => '29 KUNING MAS'],
                ['kode' => 'WRN.244', 'nama' => '30 HIJAU BOTOL', 'keterangan' => '30 HIJAU BOTOL'],
                ['kode' => 'WRN.245', 'nama' => '31 MAROON', 'keterangan' => '31 MAROON'],
                ['kode' => 'WRN.246', 'nama' => '32 NAVY', 'keterangan' => '32 NAVY'],
                ['kode' => 'WRN.247', 'nama' => '33 MISTY 71', 'keterangan' => '33 MISTY 71'],
                ['kode' => 'WRN.248', 'nama' => '34 PUTIH BLUISH', 'keterangan' => '34 PUTIH BLUISH'],
                ['kode' => 'WRN.249', 'nama' => '35 HITAM BALI', 'keterangan' => '35 HITAM BALI'],
                ['kode' => 'WRN.250', 'nama' => '36 HIJAU BOTOL', 'keterangan' => '36 HIJAU BOTOL'],
                ['kode' => 'WRN.251', 'nama' => '37 KUNING BUSUK', 'keterangan' => '37 KUNING BUSUK'],
                ['kode' => 'WRN.252', 'nama' => '38 MAROON', 'keterangan' => '38 MAROON'],
                ['kode' => 'WRN.253', 'nama' => '39 NAVY', 'keterangan' => '39 NAVY'],
                ['kode' => 'WRN.254', 'nama' => '40 BLUE REEF', 'keterangan' => '40 BLUE REEF'],
                ['kode' => 'WRN.255', 'nama' => '41 DUSTY PINK', 'keterangan' => '41 DUSTY PINK'],
                ['kode' => 'WRN.256', 'nama' => '42 TERRA COTTA', 'keterangan' => '42 TERRA COTTA'],
                ['kode' => 'WRN.257', 'nama' => '43 MISTY 71 PUTIH', 'keterangan' => '43 MISTY 71 PUTIH'],
                ['kode' => 'WRN.258', 'nama' => '1 PUTIH', 'keterangan' => '1 PUTIH'],
                ['kode' => 'WRN.259', 'nama' => '2 MISTY 71 PUTIH', 'keterangan' => '2 MISTY 71 PUTIH'],
                ['kode' => 'WRN.260', 'nama' => '3 KUNING KENARI', 'keterangan' => '3 KUNING KENARI'],
                ['kode' => 'WRN.261', 'nama' => '4 ORANGE', 'keterangan' => '4 ORANGE'],
                ['kode' => 'WRN.262', 'nama' => '5 HIJAU STABILO', 'keterangan' => '5 HIJAU STABILO'],
                ['kode' => 'WRN.263', 'nama' => '6 HIJAU FUJI', 'keterangan' => '6 HIJAU FUJI'],
                ['kode' => 'WRN.264', 'nama' => '7 HIJAU TOSCA', 'keterangan' => '7 HIJAU TOSCA'],
                ['kode' => 'WRN.265', 'nama' => '8 FANTA', 'keterangan' => '8 FANTA'],
                ['kode' => 'WRN.266', 'nama' => '9 MERAH CABE', 'keterangan' => '9 MERAH CABE'],
                ['kode' => 'WRN.267', 'nama' => '10 BIRU MUDA', 'keterangan' => '10 BIRU MUDA'],
                ['kode' => 'WRN.268', 'nama' => '11 TURQIS 1', 'keterangan' => '11 TURQIS 1'],
                ['kode' => 'WRN.269', 'nama' => '12 TURQIS 2', 'keterangan' => '12 TURQIS 2'],
                ['kode' => 'WRN.270', 'nama' => '13 BENHUR', 'keterangan' => '13 BENHUR'],
                ['kode' => 'WRN.271', 'nama' => '14 ABU TUA', 'keterangan' => '14 ABU TUA'],
                ['kode' => 'WRN.272', 'nama' => '15 COKLAT KOPI', 'keterangan' => '15 COKLAT KOPI'],
                ['kode' => 'WRN.273', 'nama' => '16 NAVY', 'keterangan' => '16 NAVY'],
                ['kode' => 'WRN.274', 'nama' => '17 HITAM', 'keterangan' => '17 HITAM'],
                ['kode' => 'WRN.275', 'nama' => '18 ABU SEDANG', 'keterangan' => '18 ABU SEDANG'],
                ['kode' => 'WRN.276', 'nama' => '19 KUNING MAS', 'keterangan' => '19 KUNING MAS'],
                ['kode' => 'WRN.277', 'nama' => '20 HIJAU BOTOL', 'keterangan' => '20 HIJAU BOTOL'],
                ['kode' => 'WRN.278', 'nama' => '21 HITAM TWOTONE', 'keterangan' => '21 HITAM TWOTONE'],
                ['kode' => 'WRN.279', 'nama' => '22 MAROON', 'keterangan' => '22 MAROON'],
                ['kode' => 'WRN.280', 'nama' => '23 MAROON TWO TONE', 'keterangan' => '23 MAROON TWO TONE'],
                ['kode' => 'WRN.281', 'nama' => '24 BENHUR TWOTONE', 'keterangan' => '24 BENHUR TWOTONE'],
                ['kode' => 'WRN.282', 'nama' => '25 HIJAU PUCUK', 'keterangan' => '25 HIJAU PUCUK'],
                ['kode' => 'WRN.283', 'nama' => '26 BIRU SEDANG', 'keterangan' => '26 BIRU SEDANG'],
                ['kode' => 'WRN.284', 'nama' => '27 BIRU MUDA', 'keterangan' => '27 BIRU MUDA'],
                ['kode' => 'WRN.285', 'nama' => '28 CREAM', 'keterangan' => '28 CREAM'],
                ['kode' => 'WRN.286', 'nama' => '29 TOSCA', 'keterangan' => '29 TOSCA'],
                ['kode' => 'WRN.287', 'nama' => '30 TURQIS TUA', 'keterangan' => '30 TURQIS TUA'],
                ['kode' => 'WRN.288', 'nama' => '31 ABU MUDA', 'keterangan' => '31 ABU MUDA'],
                ['kode' => 'WRN.289', 'nama' => '32 HIJAU TUA', 'keterangan' => '32 HIJAU TUA'],
                ['kode' => 'WRN.290', 'nama' => '33 BENHUR', 'keterangan' => '33 BENHUR'],
                ['kode' => 'WRN.291', 'nama' => '34 KUNING BUSUK', 'keterangan' => '34 KUNING BUSUK'],
                ['kode' => 'WRN.292', 'nama' => '35 KUNING TELUR', 'keterangan' => '35 KUNING TELUR'],
                ['kode' => 'WRN.293', 'nama' => '36 MAGENTA', 'keterangan' => '36 MAGENTA'],
                ['kode' => 'WRN.294', 'nama' => '37 DONGKER', 'keterangan' => '37 DONGKER'],
                ['kode' => 'WRN.295', 'nama' => '38 COKLAT', 'keterangan' => '38 COKLAT'],
                ['kode' => 'WRN.296', 'nama' => '39 ORANGE', 'keterangan' => '39 ORANGE'],
                ['kode' => 'WRN.297', 'nama' => '40 MERAH CABE', 'keterangan' => '40 MERAH CABE'],
                ['kode' => 'WRN.298', 'nama' => '41 MAROON', 'keterangan' => '41 MAROON'],
                ['kode' => 'WRN.299', 'nama' => '42 HITAM', 'keterangan' => '42 HITAM'],
                ['kode' => 'WRN.300', 'nama' => '43 MISTY TUA', 'keterangan' => '43 MISTY TUA'],
                ['kode' => 'WRN.301', 'nama' => '44 MISTY MUDA', 'keterangan' => '44 MISTY MUDA'],
                ['kode' => 'WRN.302', 'nama' => '2 KUNING GOLKAR', 'keterangan' => '2 KUNING GOLKAR'],
                ['kode' => 'WRN.303', 'nama' => '3 ABU TUA', 'keterangan' => '3 ABU TUA'],
                ['kode' => 'WRN.304', 'nama' => '4 MERAH CABE', 'keterangan' => '4 MERAH CABE'],
                ['kode' => 'WRN.305', 'nama' => '5 MAROON', 'keterangan' => '5 MAROON'],
                ['kode' => 'WRN.306', 'nama' => '6 BENHUR', 'keterangan' => '6 BENHUR'],
                ['kode' => 'WRN.307', 'nama' => '7 HIJAU BOTOL', 'keterangan' => '7 HIJAU BOTOL'],
                ['kode' => 'WRN.308', 'nama' => '8 DONGKER', 'keterangan' => '8 DONGKER'],
                ['kode' => 'WRN.309', 'nama' => '9 HITAM', 'keterangan' => '9 HITAM'],
                ['kode' => 'WRN.310', 'nama' => '10 MISTY 71', 'keterangan' => '10 MISTY 71'],
                ['kode' => 'WRN.311', 'nama' => '11 MISTY 71 PUTIH', 'keterangan' => '11 MISTY 71 PUTIH'],
                ['kode' => 'WRN.312', 'nama' => '224 HITAM', 'keterangan' => '224 HITAM'],
                ['kode' => 'WRN.313', 'nama' => '224 KUNING BUSUK', 'keterangan' => '224 KUNING BUSUK'],
                ['kode' => 'WRN.314', 'nama' => '224 MISTY 71 PUTIH', 'keterangan' => '224 MISTY 71 PUTIH'],
                ['kode' => 'WRN.315', 'nama' => '224 MERAH', 'keterangan' => '224 MERAH'],
                ['kode' => 'WRN.316', 'nama' => '224 MAROON', 'keterangan' => '224 MAROON'],
                ['kode' => 'WRN.317', 'nama' => '224 NAVY', 'keterangan' => '224 NAVY'],
                ['kode' => 'WRN.318', 'nama' => '224 PUTIH', 'keterangan' => '224 PUTIH'],
                ['kode' => 'WRN.319', 'nama' => '224 HIJAU TOSCA', 'keterangan' => '224 HIJAU TOSCA'],
                ['kode' => 'WRN.320', 'nama' => '224 ABU TUA', 'keterangan' => '224 ABU TUA'],
                ['kode' => 'WRN.321', 'nama' => '224 ABU MUDA', 'keterangan' => '224 ABU MUDA'],
                ['kode' => 'WRN.322', 'nama' => '224 HIJAU BOTOL', 'keterangan' => '224 HIJAU BOTOL'],
                ['kode' => 'WRN.323', 'nama' => '1 ABU MUDA X PUTIH', 'keterangan' => '1 ABU MUDA X PUTIH'],
                ['kode' => 'WRN.324', 'nama' => '2 ABU TUA X PUTIH', 'keterangan' => '2 ABU TUA X PUTIH'],
                ['kode' => 'WRN.325', 'nama' => '3 HITAM X PUTIH', 'keterangan' => '3 HITAM X PUTIH'],
                ['kode' => 'WRN.326', 'nama' => '4 TURQIS X PUTIH', 'keterangan' => '4 TURQIS X PUTIH'],
                ['kode' => 'WRN.327', 'nama' => '5 NAVY X PUTIH', 'keterangan' => '5 NAVY X PUTIH'],
                ['kode' => 'WRN.328', 'nama' => '6 BIRU X HITAM', 'keterangan' => '6 BIRU X HITAM'],
                ['kode' => 'WRN.329', 'nama' => '7 MERAH X PUTIH', 'keterangan' => '7 MERAH X PUTIH'],
                ['kode' => 'WRN.330', 'nama' => '8 MAROON X PUTIH', 'keterangan' => '8 MAROON X PUTIH'],
                ['kode' => 'WRN.331', 'nama' => '9 MERAH X HITAM', 'keterangan' => '9 MERAH X HITAM'],
                ['kode' => 'WRN.332', 'nama' => '10 FUJI X PUTIH', 'keterangan' => '10 FUJI X PUTIH'],
                ['kode' => 'WRN.333', 'nama' => '11 TOSCA X NAVY', 'keterangan' => '11 TOSCA X NAVY'],
                ['kode' => 'WRN.334', 'nama' => '12 COKLAT X COKLAT TUA', 'keterangan' => '12 COKLAT X COKLAT TUA'],
                ['kode' => 'WRN.335', 'nama' => '13 NAVY X TURQUIS', 'keterangan' => '13 NAVY X TURQUIS'],
                ['kode' => 'WRN.336', 'nama' => '14 MUSTARD X PUTIH', 'keterangan' => '14 MUSTARD X PUTIH'],
                ['kode' => 'WRN.337', 'nama' => '15 COKLAT X PUTIH', 'keterangan' => '15 COKLAT X PUTIH'],
                ['kode' => 'WRN.338', 'nama' => '16 TOSCA X PUTIH', 'keterangan' => '16 TOSCA X PUTIH'],
                ['kode' => 'WRN.339', 'nama' => '17 INDIGO X PUTIH', 'keterangan' => '17 INDIGO X PUTIH'],
                ['kode' => 'WRN.340', 'nama' => '18 HIJAU X PUTIH', 'keterangan' => '18 HIJAU X PUTIH'],
                ['kode' => 'WRN.341', 'nama' => '19 PUTIH X PINK', 'keterangan' => '19 PUTIH X PINK'],
                ['kode' => 'WRN.342', 'nama' => '20 MOCCA X PUTIH', 'keterangan' => '20 MOCCA X PUTIH'],
                ['kode' => 'WRN.343', 'nama' => '21 BLACK X TERRACOTTA', 'keterangan' => '21 BLACK X TERRACOTTA'],
                ['kode' => 'WRN.344', 'nama' => '22 BLUE REEF X PUTIH', 'keterangan' => '22 BLUE REEF X PUTIH'],
                ['kode' => 'WRN.345', 'nama' => '23 DUSTY GREEN X PUTIH', 'keterangan' => '23 DUSTY GREEN X PUTIH'],
                ['kode' => 'WRN.346', 'nama' => '24 MINERAL GREEN X PUTIH', 'keterangan' => '24 MINERAL GREEN X PUTIH'],
                ['kode' => 'WRN.347', 'nama' => '25 BLUSH PINK X PUTIH', 'keterangan' => '25 BLUSH PINK X PUTIH'],
                ['kode' => 'WRN.348', 'nama' => '26 LAVENDER LILAC X PUTIH', 'keterangan' => '26 LAVENDER LILAC X PUTIH'],
                ['kode' => 'WRN.349', 'nama' => '27 BIRU MARINIR X PUTIH', 'keterangan' => '27 BIRU MARINIR X PUTIH'],
                ['kode' => 'WRN.350', 'nama' => '28 CELESTIAL BLUE X PUTIH', 'keterangan' => '28 CELESTIAL BLUE X PUTIH'],
                ['kode' => 'WRN.351', 'nama' => '2 KUNING KENARI', 'keterangan' => '2 KUNING KENARI'],
                ['kode' => 'WRN.352', 'nama' => '3 KUNING KUNYIT', 'keterangan' => '3 KUNING KUNYIT'],
                ['kode' => 'WRN.353', 'nama' => '4 MUSTARD', 'keterangan' => '4 MUSTARD'],
                ['kode' => 'WRN.354', 'nama' => '5 DARK FUSCHIA', 'keterangan' => '5 DARK FUSCHIA'],
                ['kode' => 'WRN.355', 'nama' => '6 MERAH HATI', 'keterangan' => '6 MERAH HATI'],
                ['kode' => 'WRN.356', 'nama' => '7 BURGUNDY', 'keterangan' => '7 BURGUNDY'],
                ['kode' => 'WRN.357', 'nama' => '8 GRASS GREEN', 'keterangan' => '8 GRASS GREEN'],
                ['kode' => 'WRN.358', 'nama' => '9 HIJAU ARMY', 'keterangan' => '9 HIJAU ARMY'],
                ['kode' => 'WRN.359', 'nama' => '10 HIJAU BOTOL', 'keterangan' => '10 HIJAU BOTOL'],
                ['kode' => 'WRN.360', 'nama' => '11 TURQUIS TUA', 'keterangan' => '11 TURQUIS TUA'],
                ['kode' => 'WRN.361', 'nama' => '12 NAVY', 'keterangan' => '12 NAVY'],
                ['kode' => 'WRN.362', 'nama' => '13 HITAM', 'keterangan' => '13 HITAM'],
                ['kode' => 'WRN.363', 'nama' => '2 BROKEN WHITE', 'keterangan' => '2 BROKEN WHITE'],
                ['kode' => 'WRN.364', 'nama' => '3 CREAM', 'keterangan' => '3 CREAM'],
                ['kode' => 'WRN.365', 'nama' => '4 COKSU', 'keterangan' => '4 COKSU'],
                ['kode' => 'WRN.366', 'nama' => '5 COKLAT PEMDA', 'keterangan' => '5 COKLAT PEMDA'],
                ['kode' => 'WRN.367', 'nama' => '6 COKLAT MILO', 'keterangan' => '6 COKLAT MILO'],
                ['kode' => 'WRN.368', 'nama' => '7 MOCCA', 'keterangan' => '7 MOCCA'],
                ['kode' => 'WRN.369', 'nama' => '8 KOPI MUDA', 'keterangan' => '8 KOPI MUDA'],
                ['kode' => 'WRN.370', 'nama' => '9 PINK', 'keterangan' => '9 PINK'],
                ['kode' => 'WRN.371', 'nama' => '10 DARMA WANITA', 'keterangan' => '10 DARMA WANITA'],
                ['kode' => 'WRN.372', 'nama' => '11 ROSE SEDANG', 'keterangan' => '11 ROSE SEDANG'],
                ['kode' => 'WRN.373', 'nama' => '12 FANTA', 'keterangan' => '12 FANTA'],
                ['kode' => 'WRN.374', 'nama' => '13 MERAH CABE', 'keterangan' => '13 MERAH CABE'],
                ['kode' => 'WRN.375', 'nama' => '14 MERAH DARAH', 'keterangan' => '14 MERAH DARAH'],
                ['kode' => 'WRN.376', 'nama' => '15 MERAH HATI', 'keterangan' => '15 MERAH HATI'],
                ['kode' => 'WRN.377', 'nama' => '16 KOPI TUTUNG', 'keterangan' => '16 KOPI TUTUNG'],
                ['kode' => 'WRN.378', 'nama' => '17 KUNING BUSUK', 'keterangan' => '17 KUNING BUSUK'],
                ['kode' => 'WRN.379', 'nama' => '18 ORANGE', 'keterangan' => '18 ORANGE'],
                ['kode' => 'WRN.380', 'nama' => '19 BATA MUDA', 'keterangan' => '19 BATA MUDA'],
                ['kode' => 'WRN.381', 'nama' => '20 SALEM MUDA', 'keterangan' => '20 SALEM MUDA'],
                ['kode' => 'WRN.382', 'nama' => '21 SALEM TUA', 'keterangan' => '21 SALEM TUA'],
                ['kode' => 'WRN.383', 'nama' => '22 MERAH BATA', 'keterangan' => '22 MERAH BATA'],
                ['kode' => 'WRN.384', 'nama' => '24 ABU TUA', 'keterangan' => '24 ABU TUA'],
                ['kode' => 'WRN.385', 'nama' => '25 BIRU BABY', 'keterangan' => '25 BIRU BABY'],
                ['kode' => 'WRN.386', 'nama' => '26 TURQIS', 'keterangan' => '26 TURQIS'],
                ['kode' => 'WRN.387', 'nama' => '27 TOSCA MUDA', 'keterangan' => '27 TOSCA MUDA'],
                ['kode' => 'WRN.388', 'nama' => '28 TOSCA WARDAH', 'keterangan' => '28 TOSCA WARDAH'],
                ['kode' => 'WRN.389', 'nama' => '29 TOSCA SEDANG', 'keterangan' => '29 TOSCA SEDANG'],
                ['kode' => 'WRN.390', 'nama' => '30 TOSCA TUA', 'keterangan' => '30 TOSCA TUA'],
                ['kode' => 'WRN.391', 'nama' => '31 HIJAU BOTOL', 'keterangan' => '31 HIJAU BOTOL'],
                ['kode' => 'WRN.392', 'nama' => '32 BIRU ITB', 'keterangan' => '32 BIRU ITB'],
                ['kode' => 'WRN.393', 'nama' => '33 LAVENDER', 'keterangan' => '33 LAVENDER'],
                ['kode' => 'WRN.394', 'nama' => '34 FUSHIA', 'keterangan' => '34 FUSHIA'],
                ['kode' => 'WRN.395', 'nama' => '35 UNGU MUDA', 'keterangan' => '35 UNGU MUDA'],
                ['kode' => 'WRN.396', 'nama' => '36 UNGU TUA', 'keterangan' => '36 UNGU TUA'],
                ['kode' => 'WRN.397', 'nama' => '37 HIJAU HANSIP', 'keterangan' => '37 HIJAU HANSIP'],
                ['kode' => 'WRN.398', 'nama' => '38 HIJAU PANDAN', 'keterangan' => '38 HIJAU PANDAN'],
                ['kode' => 'WRN.399', 'nama' => '39 HIJAU PUPUS', 'keterangan' => '39 HIJAU PUPUS'],
                ['kode' => 'WRN.400', 'nama' => '40 HIJAU TNI', 'keterangan' => '40 HIJAU TNI'],
                ['kode' => 'WRN.401', 'nama' => '41 BENHUR', 'keterangan' => '41 BENHUR'],
                ['kode' => 'WRN.402', 'nama' => '42 NAVY', 'keterangan' => '42 NAVY'],
                ['kode' => 'WRN.403', 'nama' => '44 HIJAU PUCUK', 'keterangan' => '44 HIJAU PUCUK'],
                ['kode' => 'WRN.404', 'nama' => '45 KUNING LEMON', 'keterangan' => '45 KUNING LEMON'],
                ['kode' => 'WRN.405', 'nama' => '2 ABU MUDA', 'keterangan' => '2 ABU MUDA'],
                ['kode' => 'WRN.406', 'nama' => '3 BIRU ROYAL', 'keterangan' => '3 BIRU ROYAL'],
                ['kode' => 'WRN.407', 'nama' => '4 BLUE BLACK', 'keterangan' => '4 BLUE BLACK'],
                ['kode' => 'WRN.408', 'nama' => '5 KUNING', 'keterangan' => '5 KUNING'],
                ['kode' => 'WRN.409', 'nama' => '6 MERAH', 'keterangan' => '6 MERAH'],
                ['kode' => 'WRN.410', 'nama' => '7 ORANGE', 'keterangan' => '7 ORANGE'],
                ['kode' => 'WRN.411', 'nama' => '8 HIJAU', 'keterangan' => '8 HIJAU'],
                ['kode' => 'WRN.412', 'nama' => '9 HIJAU FUJI', 'keterangan' => '9 HIJAU FUJI'],
                ['kode' => 'WRN.413', 'nama' => '10 BIRU TUA', 'keterangan' => '10 BIRU TUA'],
                ['kode' => 'WRN.414', 'nama' => '11 MAGENTA', 'keterangan' => '11 MAGENTA'],
                ['kode' => 'WRN.415', 'nama' => '12 KHAKY', 'keterangan' => '12 KHAKY'],
                ['kode' => 'WRN.416', 'nama' => '16 PUTIH', 'keterangan' => '16 PUTIH'],
                ['kode' => 'WRN.417', 'nama' => '17 HIJAU FUJI', 'keterangan' => '17 HIJAU FUJI'],
                ['kode' => 'WRN.418', 'nama' => '18 HIJAU TOSCA', 'keterangan' => '18 HIJAU TOSCA'],
                ['kode' => 'WRN.419', 'nama' => '19 HIJAU LUMUT', 'keterangan' => '19 HIJAU LUMUT'],
                ['kode' => 'WRN.420', 'nama' => '20 TURQIS', 'keterangan' => '20 TURQIS'],
                ['kode' => 'WRN.421', 'nama' => '21 UNGU TUA', 'keterangan' => '21 UNGU TUA'],
                ['kode' => 'WRN.422', 'nama' => '22 ABU SEDANG', 'keterangan' => '22 ABU SEDANG'],
                ['kode' => 'WRN.423', 'nama' => '23 ABU TUA', 'keterangan' => '23 ABU TUA'],
                ['kode' => 'WRN.424', 'nama' => '24 BENHUR', 'keterangan' => '24 BENHUR'],
                ['kode' => 'WRN.425', 'nama' => '25 NAVY', 'keterangan' => '25 NAVY'],
                ['kode' => 'WRN.426', 'nama' => '26 KUNING', 'keterangan' => '26 KUNING'],
                ['kode' => 'WRN.427', 'nama' => '27 MERAH', 'keterangan' => '27 MERAH'],
                ['kode' => 'WRN.428', 'nama' => '28 MAROON', 'keterangan' => '28 MAROON'],
                ['kode' => 'WRN.429', 'nama' => '29 ORANGE', 'keterangan' => '29 ORANGE'],
                ['kode' => 'WRN.430', 'nama' => '30 HITAM', 'keterangan' => '30 HITAM'],
                ['kode' => 'WRN.431', 'nama' => '3 BIRU LANGIT', 'keterangan' => '3 BIRU LANGIT'],
                ['kode' => 'WRN.432', 'nama' => '4 COKLAT SUSU', 'keterangan' => '4 COKLAT SUSU'],
                ['kode' => 'WRN.433', 'nama' => '5 DUSTY PINK', 'keterangan' => '5 DUSTY PINK'],
                ['kode' => 'WRN.434', 'nama' => '6 ABU MUDA', 'keterangan' => '6 ABU MUDA'],
                ['kode' => 'WRN.435', 'nama' => '7 UNGU MUDA', 'keterangan' => '7 UNGU MUDA'],
                ['kode' => 'WRN.436', 'nama' => '8 KUNING KENARI', 'keterangan' => '8 KUNING KENARI'],
                ['kode' => 'WRN.437', 'nama' => '9 COKLAT MILO', 'keterangan' => '9 COKLAT MILO'],
                ['kode' => 'WRN.438', 'nama' => '10 FANTA', 'keterangan' => '10 FANTA'],
                ['kode' => 'WRN.439', 'nama' => '11 MERAH CABE', 'keterangan' => '11 MERAH CABE'],
                ['kode' => 'WRN.440', 'nama' => '12 MERAH HATI', 'keterangan' => '12 MERAH HATI'],
                ['kode' => 'WRN.441', 'nama' => '13 MAROON', 'keterangan' => '13 MAROON'],
                ['kode' => 'WRN.442', 'nama' => '14 TOSCA', 'keterangan' => '14 TOSCA'],
                ['kode' => 'WRN.443', 'nama' => '15 HIJAU FUJI', 'keterangan' => '15 HIJAU FUJI'],
                ['kode' => 'WRN.444', 'nama' => '16 HIJAU TNI', 'keterangan' => '16 HIJAU TNI'],
                ['kode' => 'WRN.445', 'nama' => '17 HIJAU BOTOL', 'keterangan' => '17 HIJAU BOTOL'],
                ['kode' => 'WRN.446', 'nama' => '18 KUNING BUSUK', 'keterangan' => '18 KUNING BUSUK'],
                ['kode' => 'WRN.447', 'nama' => '19 ORANGE TUA', 'keterangan' => '19 ORANGE TUA'],
                ['kode' => 'WRN.448', 'nama' => '20 COKLAT KOPI', 'keterangan' => '20 COKLAT KOPI'],
                ['kode' => 'WRN.449', 'nama' => '21 BENHUR', 'keterangan' => '21 BENHUR'],
                ['kode' => 'WRN.450', 'nama' => '22 ABU SMA', 'keterangan' => '22 ABU SMA'],
                ['kode' => 'WRN.451', 'nama' => '24 NAVY', 'keterangan' => '24 NAVY'],
                ['kode' => 'WRN.452', 'nama' => '25 HITAM', 'keterangan' => '25 HITAM'],
                ['kode' => 'WRN.453', 'nama' => '1 PUTIH', 'keterangan' => '1 PUTIH'],
                ['kode' => 'WRN.454', 'nama' => '2 KUNING MAS', 'keterangan' => '2 KUNING MAS'],
                ['kode' => 'WRN.455', 'nama' => '3 KUNING KENARI', 'keterangan' => '3 KUNING KENARI'],
                ['kode' => 'WRN.456', 'nama' => '4 ORANGE', 'keterangan' => '4 ORANGE'],
                ['kode' => 'WRN.457', 'nama' => '5 PINK', 'keterangan' => '5 PINK'],
                ['kode' => 'WRN.458', 'nama' => '6 MERAH CABE', 'keterangan' => '6 MERAH CABE'],
                ['kode' => 'WRN.459', 'nama' => '7 MERAH HATI', 'keterangan' => '7 MERAH HATI'],
                ['kode' => 'WRN.460', 'nama' => '8 TOSCA', 'keterangan' => '8 TOSCA'],
                ['kode' => 'WRN.461', 'nama' => '9 HIJAU STABILO', 'keterangan' => '9 HIJAU STABILO'],
                ['kode' => 'WRN.462', 'nama' => '10 HIJAU FUJI', 'keterangan' => '10 HIJAU FUJI'],
                ['kode' => 'WRN.463', 'nama' => '11 HIJAU FUJI', 'keterangan' => '11 HIJAU FUJI'],
                ['kode' => 'WRN.464', 'nama' => '12 HIJAU SUPER', 'keterangan' => '12 HIJAU SUPER'],
                ['kode' => 'WRN.465', 'nama' => '13 HIJAU TNI', 'keterangan' => '13 HIJAU TNI'],
                ['kode' => 'WRN.466', 'nama' => '14 UNGU TUA', 'keterangan' => '14 UNGU TUA'],
                ['kode' => 'WRN.467', 'nama' => '15 BIRU BABY', 'keterangan' => '15 BIRU BABY'],
                ['kode' => 'WRN.468', 'nama' => '16 BIRU SDG', 'keterangan' => '16 BIRU SDG'],
                ['kode' => 'WRN.469', 'nama' => '17 TURQIS', 'keterangan' => '17 TURQIS'],
                ['kode' => 'WRN.470', 'nama' => '18 BENHUR', 'keterangan' => '18 BENHUR'],
                ['kode' => 'WRN.471', 'nama' => '19 BENHUR', 'keterangan' => '19 BENHUR'],
                ['kode' => 'WRN.472', 'nama' => '20 NAVY', 'keterangan' => '20 NAVY'],
                ['kode' => 'WRN.473', 'nama' => '21 HITAM', 'keterangan' => '21 HITAM'],
                ['kode' => 'WRN.474', 'nama' => '22 ABU SEDANG', 'keterangan' => '22 ABU SEDANG'],
                ['kode' => 'WRN.475', 'nama' => '23 COKLAT KOPI', 'keterangan' => '23 COKLAT KOPI'],
                ['kode' => 'WRN.476', 'nama' => '24 COKLAT TUTUNG', 'keterangan' => '24 COKLAT TUTUNG'],
                ['kode' => 'WRN.477', 'nama' => '25 FANTA', 'keterangan' => '25 FANTA'],
                ['kode' => 'WRN.478', 'nama' => '26 FANTA UTAMA', 'keterangan' => '26 FANTA UTAMA'],
                ['kode' => 'WRN.479', 'nama' => 'MUDA', 'keterangan' => 'MUDA'],
                ['kode' => 'WRN.480', 'nama' => 'SEDANG', 'keterangan' => 'SEDANG'],
                ['kode' => 'WRN.481', 'nama' => 'TUA', 'keterangan' => 'TUA'],
                ['kode' => 'WRN.482', 'nama' => 'TUA SPESIAL', 'keterangan' => 'TUA SPESIAL'],
                ['kode' => 'WRN.483', 'nama' => 'HITAM SULFUR', 'keterangan' => 'HITAM SULFUR'],
                ['kode' => 'WRN.484', 'nama' => 'ALL COLOUR', 'keterangan' => 'ALL COLOUR'],
                ['kode' => 'WRN.485', 'nama' => 'TWO TONE', 'keterangan' => 'TWO TONE'],
                ['kode' => 'WRN.486', 'nama' => 'RAINBOW TW', 'keterangan' => 'RAINBOW TW'],
                ['kode' => 'WRN.487', 'nama' => 'M71', 'keterangan' => 'M71'],
                ['kode' => 'WRN.488', 'nama' => 'M71 PUTIH', 'keterangan' => 'M71 PUTIH'],
                ['kode' => 'WRN.489', 'nama' => 'M81', 'keterangan' => 'M81'],
                ['kode' => 'WRN.490', 'nama' => 'M61 PUTIH', 'keterangan' => 'M61 PUTIH'],
                ['kode' => 'WRN.491', 'nama' => 'PUTIH', 'keterangan' => 'PUTIH'],
                ['kode' => 'WRN.492', 'nama' => '-', 'keterangan' => '-']
            ],
            ['kode'],
            ['nama', 'keterangan']
        );
    }
}
